Repository NCAS-CMS/cfdm, pull requests merged in 2023-06, with the labels that each got.

#258 Stop `FutureWarning` originating from `NetCDFWrite._character_array`
  cfdm/read_write/netcdf/netcdfwrite.py
Labels: code tidy/refactor

#257 Scrollable Navigation Menu (Sidebar)
  docs/_static/alabaster.css
  docs/source/_static/customise-alabaster.css
  docs/source/conf.py
Labels: documentation

#261 Fix very slow reads of datasets with compession by gathering or DSG ragged arrays
  Changelog.rst
  cfdm/cfdmimplementation.py
  cfdm/core/__init__.py
  cfdm/data/data.py
  cfdm/read_write/netcdf/netcdfread.py
Labels: bug, performance

#263 Fix bug the prevented `cfdm.read` form accessing remote files in URL locations
  Changelog.rst
  cfdm/read_write/netcdf/netcdfread.py
  cfdm/read_write/read.py
  cfdm/test/test_read_write.py
Labels: bug

#264 Docs: remove or replace cases of some subjective filler terms
  docs/source/extensions.rst
  docs/source/introduction.rst
  docs/source/tutorial.rst
Labels: documentation
